### ISSUE TITLE
Update fails with "line 30: pushd: plugins/*: No such file or directory"

### ISSUE THREAD

**Issue by bayendor** [rkh/rbenv-update#21] opened 2015-03-31 23:02 UTC
After recently updating my rbenv install using `rbenv update` I know get this error:

```
$ rbenv update
updating rbenv
 |  Already up-to-date.

/~/.rbenv/plugins/rbenv-update/bin/rbenv-update: line 30: pushd: plugins/*: No such file or directory
```
Prior to this everything worked fine.  I examined the error on line 30 of `/bin/rbenv-update` it seems to be related to the change made in commit 23b129e.  

Changing line 30 to `cd ${RBENV_ROOT:-$(rbenv root)}` seems to fix the problem.

However, the plugin `ruby-build` now gets the error `Not an rbenv git repo; skipping...`  I believe this is related to commit 5b7abaf.  The `grep` command does not return `rbenv`.  This can be fixed with:

```
is_rbenv_git_repo() {
  $(git remote -v | grep -E 'rbenv|ruby-build' &>/dev/null)
}
```

Let me know if I'm off base with this, or if you'd like me to submit a PR with the either or both of these changes.

**Comment by jasonkarns** [comment] 2015-04-01 00:03
Yeah, submit a pr for the grep update. (Separately from the CD path issue)

The rbenv root issue confuses me because rbenv guarantees that $RBENV_ROOT
is set. In fact, rbenv root command does nothing except echo the variable
value.

Can you provide some more details on how you're executing rbenv update?

**Comment by bayendor** [comment] 2015-04-01 00:12
PR submitted for the grep issue.

**Comment by bayendor** [comment] 2015-04-01 00:15
When I `echo $RBENV_ROOT` I get nothing back.
When I `echo $(rbenv root)` => `/Users/David/.rbenv`, which is correct.

I update using `rbenv update` about twice a month, and this is the first time I've ever experienced this problem.

Have I somehow missed a configuration issue or setting `RBENV_ROOT` in my `.bash_profile`?

**Comment by jasonkarns** [comment] 2015-04-01 00:18
No, it certainly isn't a lack of configuration.

How do you invoke rbenv update? Just `rbenv update`, correct? You're not
executing the rbenv-update bin directly are you?

**Comment by bayendor** [comment] 2015-04-01 00:21
Correct, executed simply as `rbenv update` at the command line, typically from the home directory.

**Comment by jasonkarns** [comment] 2015-04-01 01:12
@bayendor i've merged the ruby-build grep piece (thanks!) but i'm having trouble replicating the `$RBENV_ROOT` issue.

My normal setup is rbenv through homebrew (and installed in `/usr/local/var`), plugins through git, which `$RBENV_ROOT` set explicitly. However, to test this issue, I switched to the common setup: rbenv installed to `~/.rbenv` through git, `$RBENV_ROOT` unset. With this setup, `rbenv update` worked fine for me.

I'd really like to get to the bottom of it because it sounds like it may actually be a bug in rbenv itself (since rbenv is responsible for ensuring $RBENV_ROOT is set for the execution of a plugin). We could certainly revert the change that caused this bug, but that really *shouldn't* be necessary.

1. What's your OS?
2. Which shell are you using?
3. Which version of rbenv are you using?
4. What does your shell initialization look like with respect to rbenv? (Where/how do you have rbenv initialized?)
5. What's your `$PATH` look like?

Or even better, would you mind pairing on this?

**Comment by jasonkarns** [comment] 2015-04-01 01:16
code in rbenv that ought to be responsible for ensuring $RBENV_ROOT is set:

https://github.com/sstephenson/rbenv/blob/d1a0398fdb99b548fd3846228e61f096b6982e60/libexec/rbenv#L50-L55

Also relevant: https://github.com/sstephenson/rbenv/blob/07d675350fd0f7a357daa4a237fe2da865e5ec64/libexec/rbenv-rehash#L63

**Comment by bayendor** [comment] 2015-04-01 01:40
I would be quite happy to pair with you.  How would like to do that, ScreenHero, Google Hangout, SSH?

In the meantime: 

1. OS X 10.10.2
2. GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
3. rbenv 0.4.0-146-g7ad01b2
4. https://github.com/bayendor/.dotfiles/blob/master/bash_profile#L20-L22
5. `/Users/David/.rbenv/shims:/Users/David/.rbenv/bin:/usr/local/bin:/usr/local/sbin:~/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/lib`
6. Text file located here: http://cl.ly/aSDF

**Comment by jasonkarns** [comment] 2015-04-01 01:54
I just hit you up on hangouts (I think). screenhero would be fine. my screenhero email is jason@karns.name

**Comment by jasonkarns** [comment] 2015-04-01 02:21
fixed again with #23, but what seems like a potential root cause is rbenv invoking rbenv-sh-update instead of rbenv-update. (which causes an additional rbenv-init)

**Comment by jasonkarns** [comment] 2015-04-01 12:40
@bayendor sorry to ping you again... could you post the link to that last debug capture that we took last night? I'd like to get this opened as a ticket on rbenv proper.

**Comment by bayendor** [comment] 2015-04-01 12:54
Link for the debug output: http://cl.ly/aSNT

**Comment by jasonkarns** [comment] 2015-04-01 13:56
opened issue upstream with rbenv to figure out why rbenv-sh-update is being invoked instead of rbenv-update. https://github.com/sstephenson/rbenv/issues/715

@rkh do you have any insight into why this would be happening? (Or more background info into the purpose of rbenv-sh-update?)

**Closed** 2015-10-11 19:56 UTC
